// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIv0a5kfG-RiXR5dPME27oVoyrN0jxCGI',
    appId: '1:549383909930:web:76156b955df2b27b710953',
    messagingSenderId: '549383909930',
    projectId: 'arunaapp-8f11c',
    authDomain: 'arunaapp-8f11c.firebaseapp.com',
    storageBucket: 'arunaapp-8f11c.firebasestorage.app',
    measurementId: 'G-CMW54CZWRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBPet8wtzJo46B2sNnmDXAR7zzl8e4lJE',
    appId: '1:549383909930:android:0cefe34109e9dce1710953',
    messagingSenderId: '549383909930',
    projectId: 'arunaapp-8f11c',
    storageBucket: 'arunaapp-8f11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAACCHa_f2ESCMPnmnkX3pjlwEwgQHdqnQ',
    appId: '1:549383909930:ios:3ad439b0ff3ea0c5710953',
    messagingSenderId: '549383909930',
    projectId: 'arunaapp-8f11c',
    storageBucket: 'arunaapp-8f11c.firebasestorage.app',
    iosBundleId: 'com.example.arunaapp',
  );

}